const data = [
    {
      id: 1,
      name: "Apple",
      price: 3500,
      image: "https://iranfreshfruit.net/wp-content/uploads/2020/01/red-apple-fruit-600x600.jpg",
      category: "Fruits",
    },
    {
      id: 2,
      name: "Fresh Mango",
      price: 6539,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4I6yRYIENEwD7FoYR3cnWy2q4BKYfFwSotA&s",
      category: "Fruits",
    },
    {
      id: 3,
      name: "Fresh Banana",
      price: 1249,
      image: "https://img.freepik.com/free-photo/single-banana-isolated-white-background_839833-17794.jpg",
      category: "Fruits",
    },
    {
      id: 4,
      name: "Fresh Watermelon",
      price: 620,
      image: "https://5.imimg.com/data5/SELLER/Default/2022/12/DM/EC/KE/49293026/fresh-watermelon-fruit.webp",
      category: "Fruits",
    },
    {
      id: 5,
      name: "Fresh Lychee",
      price: 570,
      image: "https://png.pngtree.com/png-clipart/20231127/original/pngtree-single-fruit-lychee-cartoon-png-image_13719513.png",
      category: "Fruits",
    },
    {
      id: 6,
      name: "Koenigsegg Gemera",
      price: 2100000,
      image: "https://cdn1.vectorstock.com/i/1000x1000/99/85/headphone-black-music-earphone-or-gaming-headset-vector-35439985.jpg",
      category: "Cars",
    },
    {
      id: 7,
      name: "New Electric Car",
      price: 35000,
      image: "https://m.media-amazon.com/images/I/61+r3+JstZL._AC_UF1000,1000_QL80_.jpg",
      category: "Cars",
    },
    {
      id: 8,
      name: "Smart Refrigerator",
      price: 1500,
      image: "https://www.sathya.store/img/product/hPsJidGgc0hyMpo1.png",
      category: "Electronics",
    },
    {
      id: 9,
      name: "Wireless Headphones",
      price: 300,
      image: "https://m.media-amazon.com/images/I/51EbaSTGcqL.jpg",
      category: "Electronics",
    },
    {
      id: 10,
      name: "Samsung Washing Machine",
      price: 600,
      image: "https://www.afcinternationalllc.com/wp-content/uploads/2016/07/AFC-Importing-Electronics-1-7-7-16.jpg",
      category: "Electronics",
    },
    {
      id: 11,
      name: "Designer Artificial Jewellery",
      price: 4999,
      image: "https://5.imimg.com/data5/TG/DN/MY-37294786/designer-artificial-jewellery.jpg",
      category: "Jewelry",
    },
    {
      id: 12,
      name: "Elegant Gold Jewellery",
      price: 8999,
      image: "https://img.etimg.com/thumb/width-1600,height-900,imgsize-164838,resizemode-75,msid-106210151/industry/cons-products/fashion-/-cosmetics-/-jewellery/jewellery-consumption-to-grow-by-10-12-value-wise-in-fy24-amid-rise-in-gold-prices-report.jpg",
      category: "Jewelry",
    },
    {
      id: 13,
      name: "Diamond Ring",
      price: 12999,
      image: "https://static.vecteezy.com/system/resources/previews/022/899/918/non_2x/jewelry-ring-with-diamonds-and-precious-stones-ai-generated-free-photo.jpg",
      category: "Jewelry",
    },
    {
      id: 14,
      name: "Luxury Pendant",
      price: 15999,
      image: "https://kinclimg0.bluestone.com/f_webp,c_scale,w_1024,b_rgb:f0f0f0/giproduct/BIDG0412R02_YAA18DIG6XXXXXXXX_ABCD00-PICS-00001-1024-34991.png",
      category: "Jewelry",
    },
    {
      id: 15,
      name: "Slim Fit Bomber Jacket",
      price: 3500,
      image: "https://specials-images.forbesimg.com/imageserve/615b0aad1415a9fbb4f49bac/Best-Men-s-Clothing--Sandbank-Men-s-Slim-Fit-Lightweight-Sportswear-Flight-Bomber/0x800.jpg?cropX1=0&cropX2=1279&cropY1=0&cropY2=1500",
      category: "Men's Clothing",
    },
    {
      id: 16,
      name: "Summer Sale T-Shirt",
      price: 1200,
      image: "https://images-eu.ssl-images-amazon.com/images/G/31/img16/men-apparel/FNL-Sale/Symbol-40-60._V530413733_.jpg",
      category: "Men's Clothing",
    },
    {
      id: 17,
      name: "Casual Shirt",
      price: 1800,
      image: "https://thehouseofrare.com/cdn/shop/products/HERO_b4ebad16-bb9b-4e74-9675-cd50d3126091_765x.jpg?v=1709534074",
      category: "Men's Clothing",
    },
    {
      id: 18,
      name: "Checked Cotton Shirt",
      price: 1500,
      image: "https://www.beyoung.in/api/cache/catalog/products/new_checked_shirt_image_9_12_2022/pista_green_cotton_solid_shirts_for_men_base_02_05_2024_700x933.jpg",
      category: "Men's Clothing",
    },
    {
      id: 19,
      name: "Stylish Jacket",
      price: 2200,
      image: "https://m.media-amazon.com/images/I/71On2XSPuRL._SY741_.jpg",
      category: "Men's Clothing",
    },
    {
      id: 20,
      name: "Green A-Line Dress",
      price: 3999,
      image: "https://www.fablestreet.com/_next/image?url=https%3A%2F%2Fcdn.shopify.com%2Fs%2Ffiles%2F1%2F0486%2F0634%2F7416%2Fproducts%2FPeter_20Pan_20Collar_20Pleated_20A_20Line_20Dress_20-_20Green_L2.jpg%3Fv%3D1615471285&w=1920&q=75",
      category: "Women's Clothing",
    },
    {
      id: 21,
      name: "White Caledon Dress",
      price: 4999,
      image: "https://www.rareism.com/cdn/shop/files/caledonwhite__caledon-white08915_49073d14-1dc2-4bca-a668-72d4513d24c1_765x.jpg?v=1721040785",
      category: "Women's Clothing",
    },
    {
      id: 22,
      name: "Elegant Evening Dress",
      price: 5999,
      image: "https://m.media-amazon.com/images/I/71NR4MwqkjL._SY741_.jpg",
      category: "Women's Clothing",
    },
    {
      id: 23,
      name: "Knitted Dress",
      price: 2899,
      image: "https://twinbirds.co.in/cdn/shop/files/KNITTEDDRESSES.jpg?v=1694418486&width=600",
      category: "Women's Clothing",
    },
    
  ];
  
  export default data;